#!/usr/bin/env python3
"""
setup_vendor.py - Generate vendor/samsung/a02/ from raw vendor blobs
Usage: python3 setup_vendor.py --src <vendor_src> --dst <vendor_dst>
"""

import os, sys, shutil, argparse, subprocess
from pathlib import Path

# Libs that conflict with AOSP/MT6739 framework - use vendor-prefixed names
CONFLICT_LIBS = {
    "android.hardware.camera.provider@2.4.so",
    "android.hardware.camera.provider@2.5.so",
    "android.hardware.camera.provider@2.6.so",
    "libalsautils.so",
    "libbluetooth_audio_session.so",
    "libdownmix.so",
    "libril.so",
    "libstagefright_amrnb_common.so",
}

# Files that must NOT go in PRODUCT_COPY_FILES (managed elsewhere)
SKIP_COPY_FILES = {
    "vendor/etc/init",
    "vendor/etc/selinux",
    "vendor/bin",
    "vendor/etc/group",
    "vendor/etc/passwd",
    "vendor/etc/fs_config_files",
    "vendor/etc/fs_config_dirs",
    "vendor/ueventd.rc",
    "vendor/build.prop",
    "vendor/apex",
    "vendor/app",
    "vendor/etc/vintf",
}

def should_skip(rel_path: str) -> bool:
    for skip in SKIP_COPY_FILES:
        if rel_path.startswith(skip):
            return True
    return False

def is_conflict_lib(filename: str) -> bool:
    return filename in CONFLICT_LIBS

def collect_blobs(src: Path):
    blobs = {"so": [], "bin": [], "etc": [], "apex": [], "app": [], "other": []}
    vendor_root = src / "vendor"
    if not vendor_root.exists():
        vendor_root = src  # fallback: root IS vendor/

    for f in sorted(vendor_root.rglob("*")):
        if not f.is_file():
            continue
        # Pastiin file masih di bawah vendor_root
        try:
            rel = f.relative_to(vendor_root)
        except ValueError:
            print(f"[skip] path outside vendor_root: {f}")
            continue
        rel_str = str(rel)
        # Skip jika path mulai dengan .. (escape dari vendor_root)
        if rel_str.startswith(".."):
            print(f"[skip] relative escape path: {rel_str}")
            continue
        # Skip generated files dari run sebelumnya
        if f.name in ("Android.bp", "Android.mk", "BoardConfigVendor.mk"):
            continue
        if should_skip(rel_str):
            continue
        ext = f.suffix
        name = f.name
        if ext == ".so":
            blobs["so"].append((f, rel))
        elif name in ("bin",) or "bin/" in rel_str:
            blobs["bin"].append((f, rel))
        elif ext == ".apex":
            blobs["apex"].append((f, rel))
        elif ext == ".apk":
            blobs["app"].append((f, rel))
        elif "etc/" in rel_str:
            blobs["etc"].append((f, rel))
        else:
            blobs["other"].append((f, rel))
    return blobs

def write_android_bp(dst: Path, so_blobs: list):
    lines = ['// AUTO-GENERATED by setup_vendor.py', 'soong_namespace {}', '']
    for f, rel in so_blobs:
        name = f.stem  # libfoo
        is_conflict = is_conflict_lib(f.name)
        module_name = f"vendor_a02_{name}" if is_conflict else name
        rel_str = str(rel).replace("\\", "/")
        lines += [
            'cc_prebuilt_library_shared {',
            f'    name: "{module_name}",',
            f'    srcs: ["{rel_str}"],',
            '    vendor: true,',
            '    strip: { none: true },',
            '    check_elf_files: false,',
            '    prefer: true,',
            '}',
            '',
        ]
    bp_file = dst / "Android.bp"
    bp_file.write_text("\n".join(lines))
    print(f"[+] Android.bp written ({len(so_blobs)} libs)")

def write_android_mk(dst: Path, blobs: dict):
    lines = [
        'LOCAL_PATH := $(call my-dir)',
        'include $(CLEAR_VARS)',
        '',
        '# Vendor blobs for Samsung Galaxy A02 (MT6739)',
        '# AUTO-GENERATED by setup_vendor.py',
        '',
        'PRODUCT_COPY_FILES += \\',
    ]
    copy_entries = []

    for category in ("etc", "other"):
        for f, rel in blobs[category]:
            rel_str = str(rel).replace("\\", "/")
            # Skip jika path tidak valid
            if rel_str.startswith("..") or rel_str.startswith("/"):
                continue
            copy_entries.append(f'    $(LOCAL_PATH)/{rel_str}:$(TARGET_COPY_OUT_VENDOR)/{rel_str}')

    lines.append(" \\\n".join(copy_entries))
    lines.append("")

    mk_file = dst / "Android.mk"
    mk_file.write_text("\n".join(lines))
    print(f"[+] Android.mk written")

def copy_blobs(src: Path, dst: Path, blobs: dict):
    dst.mkdir(parents=True, exist_ok=True)
    total = 0
    for category, items in blobs.items():
        for f, rel in items:
            target = dst / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, target)
            total += 1
    print(f"[+] Copied {total} blobs to {dst}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--dst", required=True)
    args = ap.parse_args()

    src = Path(args.src)
    dst = Path(args.dst)

    print(f"[*] Collecting blobs from {src}")
    blobs = collect_blobs(src)

    for cat, items in blobs.items():
        print(f"    {cat}: {len(items)} files")

    print(f"[*] Copying to {dst}")
    copy_blobs(src, dst, blobs)

    print(f"[*] Writing Android.bp")
    write_android_bp(dst, blobs["so"])

    print(f"[*] Writing Android.mk")
    write_android_mk(dst, blobs)

    print("[*] Done. Vendor tree ready.")

if __name__ == "__main__":
    main()
