# Inherit MediaTek common
-include vendor/samsung/a02/BoardConfigVendor.mk

DEVICE_PATH := device/samsung/a02

TARGET_BOARD_PLATFORM := mt6739
TARGET_BOOTLOADER_BOARD_NAME := k39tv1_bsp_titan_hamster
TARGET_NO_BOOTLOADER := true

# ARM 32-bit (NO lib64)
TARGET_ARCH         := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI      := armeabi-v7a
TARGET_CPU_ABI2     := armeabi
TARGET_CPU_VARIANT  := cortex-a53
TARGET_2ND_ARCH     :=

# Kernel
BOARD_KERNEL_BASE        := 0x40000000
BOARD_KERNEL_PAGESIZE    := 2048
BOARD_RAMDISK_OFFSET     := 0x11b00000
BOARD_KERNEL_TAGS_OFFSET := 0x07880000
BOARD_BOOT_HEADER_VERSION := 2
BOARD_KERNEL_IMAGE_NAME  := zImage
TARGET_PREBUILT_KERNEL   := $(DEVICE_PATH)/prebuilt/zImage
BOARD_MKBOOTIMG_ARGS     := --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
                            --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
                            --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_KERNEL_CMDLINE     := bootopt=64S3,32S1,32S1 androidboot.selinux=permissive

# Partitions
BOARD_FLASH_BLOCK_SIZE   := 131072
BOARD_SUPER_PARTITION_SIZE := 1610612736
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 1606418432
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 104857600
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR  := vendor
TARGET_COPY_OUT_PRODUCT := product

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# SELinux (permissive for dev)
SELINUX_IGNORE_NEVERALLOWS := true
BOARD_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# HIDL
DEVICE_MANIFEST_FILE    := $(DEVICE_PATH)/manifest.xml
DEVICE_MATRIX_FILE      := $(DEVICE_PATH)/compatibility_matrix.xml
