name: 1. Setup Vendor & Device Tree

on:
  workflow_dispatch:

env:
  VENDOR_REPO: cipin23/vendorgw

jobs:
  setup-trees:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: out_repo
        ref: build

    - name: Clone blobs
      run: git clone --depth=1 https://github.com/$VENDOR_REPO.git vendor_src

    - name: Generate Trees
      run: |
        rm -rf out_repo/vendor/samsung/a02
        python3 out_repo/scripts/setup/setup_vendor.py \
          --src $(pwd)/vendor_src \
          --dst $(pwd)/out_repo/vendor/samsung/a02
        
        python3 out_repo/scripts/setup/gen_device_tree.py \
          --vendor-src $(pwd)/vendor_src \
          --out $(pwd)/out_repo/device/samsung/a02

    - name: Verifikasi
      run: |
        ls -R out_repo/vendor/samsung/a02/
        if [ -f out_repo/vendor/samsung/a02/a02-vendor.mk ]; then
          echo "MANTAP! File a02-vendor.mk kebentuk."
        else
          echo "MASIH GAK ADA!" && exit 1
        fi

    - name: Commit & Push
      run: |
        cd out_repo
        git config user.name "Arrow Tree Bot"
        git config user.email "bot@arrow.local"
        git add .
        git commit -m "Fix: Handled recursive file copy on build branch [skip ci]" || exit 0
        git push origin build
